---
gw_fff_wireguard:
  wg_jupiter:
    secret_key: "{{ vault_gw_fff_wireguard.wg0.secret_key }}"
    public_key: 0Lqb11k+bnjuGnkrazXVYTV0r2UJpsZMdRLlqfnN7GQ=
    listen_port: 51820
    ip4_address: "10.83.252.115/32"
    ip6_address: "fe80::4c51:4231:1/64"
    peers:
    - public_key: wZ4bZ5b1Xc1izp6RPIHbHxjj1A+OqOzEObhu0WuRmGc=
      endpoint: jupiter.dresel.systems:31345
      allowed_ips: "0.0.0.0/0, ::0/0"
      persistent_keepalive: "25"
    interface_template: wg-babel-peer.j2
  wg1:
    secret_key: "{{ vault_gw_fff_wireguard.wg1.secret_key }}"
    public_key: 1LQbPGGxRyFSA7ZKBegU36TPkYC1vMf0kF3U17Fh12Y=
    listen_port: 51821
    ip4_address: "10.83.9.1/24"
    ip4_network: "10.83.9.0/24"
    ip6_address: "fe80::4c51:4232:1/64"
    peers:
    - public_key: 2lqB+n8qUlvr1QN6Mxm8mH0Qj8hvfZz3AHuK1WGm3SQ=
      allowed_ips: 10.83.9.0/24
    interface_template: wg-babel-announce.j2



gw_fff_network:
  ip4:
    address: 10.83.9.1/24
  ip6:
    address:

gw_fff_babel:
  - interface: wg_jupiter
    type: tunnel
    rxcost: 4096
